In [ ]:
A = 1
B = 1
C = 1
A + B + C

In [ ]:
1A = 1

In [ ]:
a 1 = 1

In [ ]:
a_1 = 1

In [ ]:
_a1 = 1                            

In [ ]:
__a = 1

In [ ]:
a@gmail.com = 1

In [ ]:
if = 2

In [ ]:
count = 100
kilometres = 1000.0
name = 'Rahul'

In [ ]:
print(count,kilometres,name)

In [ ]:
a,b,c = 1,2,"Diwakar"
print(a,b,c)

In [ ]:
a=b=c=1
print(a,b,c)

In [ ]:
print(id(a))
print(id(b))
print(id(c))

In [ ]:
a=1
b=1
c=1
print(id(a))
print(id(b))
print(id(c))

In [ ]:
type(a)

In [ ]:
del a

In [ ]:
a

In [ ]:
id(a)

In [ ]:
b=3.13j

In [ ]:
type(b)

In [ ]:
str1="Python is a programming language"
print(str1)

In [ ]:
a=1
a*2

In [ ]:
str1="Python is a programming language"
print(str1*2)

In [ ]:
str2="Hi"
print(str1+str2)

In [ ]:
a=1
print(id(a))

In [ ]:
a=2
id(a)

## String

In [ ]:
str1="Python is a programming language"
print(str1[0])

In [ ]:
print(str1[2:10])

In [ ]:
print(str1[6:18])

In [ ]:
print(str1[12:23])

In [ ]:
str1.split()

In [ ]:
str = "{} {} {}".format("I","am","good")
str

In [ ]:
str = "{1} {0} {2}".format("I","am","good")
str

In [ ]:
String1 = "{a} {e} {c}".format(a='Python',e='Programming',c='Language')
print(String1)

In [ ]:
str1.capitalize()

In [ ]:
str1.upper()

## List

In [ ]:
L = [1,2,3,'abes',12.5]
L

In [ ]:
type(L)

In [ ]:
L[0:3]

In [ ]:
L[3][2]

In [ ]:
ks=[1,2,3]
ks+ks

In [ ]:
ls=[7,8,9]
ks+ls

In [ ]:
ks*5

In [ ]:
ks*ks

In [ ]:
L

In [ ]:
id(L[0])

In [ ]:
L[0] = 10
L

In [ ]:
id(L[0])

In [ ]:
id(L)

In [ ]:
L2="Diwakar"
print(id(L2))

In [ ]:
L2[0]="G"
L2 

In [ ]:
L2="G"+L2[1:]
L2

In [ ]:
id(L2)

## Input

In [ ]:
a = input("Enter your name? ")

In [ ]:
type(a)

In [ ]:
b = (input("Enter your age? "))
print(b)

In [ ]:
type(b)

In [ ]:
b*2

In [ ]:
b = int(input("Enter your age? "))
print(b*2)

In [ ]:
a = input("Enter your sequence")

In [ ]:
a

In [ ]:
type(a)

In [ ]:
a.split( )

## Tuple

In [ ]:
tuple1 = ('abcd',786,2.23,'john',70.2)
tuple2 = (123,'john')

In [ ]:
print(tuple1)

In [ ]:
print(tuple2)

In [ ]:
print(tuple1+tuple2)

In [ ]:
tuple1[0]

In [ ]:
tuple[0]="Hi"

In [ ]:
print(tuple1*4,end="")

## Dictionary  {key:value}

In [ ]:
dict1 = {}

In [ ]:
type(dict1)

In [ ]:
dict1['one'] = "This is Python"
dict1[2] = "This is Java"
dict1

In [ ]:
dict1[2]

In [ ]:
dict1[3]

In [ ]:
dict2 = {'name':'Akshay','id':1234,'dept':'technical'}
dict2

In [ ]:
dict2['name']

In [ ]:
dict2['id']

In [ ]:
print(dict2.keys())

In [ ]:
dict2.values()

## Loops

### While loop

In [ ]:
count = 0
while(count<10):
    print(count)
    count=count+1

### While loop with else

In [ ]:
count = 0
while(count < 5):
    print(count,"is less than 5")
    count=count+1
else:
    print(count,"is not less than 5")

### For Loop

In [ ]:
a = [1,2,34,56,78]
for i in a:
    print(i)

In [ ]:
name = input("Enter your name? ")

In [ ]:
name[0]

In [ ]:
total = 0
for i in name:
    print(i)
    total = total+1

print(total)

# Numpy

In [ ]:
a=[2,3]

In [ ]:
a*2

In [ ]:
import numpy 

In [ ]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
a_n=np.array(a)

In [ ]:
a_n

In [ ]:
a_n*2

In [ ]:
type(a_n)

In [ ]:
marks=[54,48,69,72,39,92,87,45,23,80]
marks=np.array(marks)

In [ ]:
np.amin(marks)

In [ ]:
np.amax(marks)

In [ ]:
np.min(marks)

In [ ]:
np.max(marks)

In [ ]:
np.mean(marks)

In [ ]:
np.median(marks)

In [ ]:
np.ptp(marks)

In [ ]:
np.std(marks)

In [ ]:
np.var(marks)

In [ ]:
np.average(marks)

In [ ]:
np.percentile(marks,10)

In [ ]:
x = [34,45,67,78]
x=np.array(x)

In [ ]:
np.mean(x)

In [ ]:
np.std(x)

In [ ]:
ss=np.mean((x-np.mean(x))**2)
ss

In [ ]:
np.sqrt(ss)

In [1]:
from numpy import random

In [2]:
random.rand()

0.726424320012187

In [7]:
random.seed(12)
for i in range(10):
    print(random.rand())

0.15416284237967237
0.7400496965154048
0.26331501518513467
0.5337393933802977
0.014574962485419674
0.918747008099885
0.9007148541170122
0.03342142762634459
0.9569493362751168
0.13720932135607644


In [4]:
x=2.75

In [5]:
x=1+(1-3.5)*x
x

-5.875

In [6]:
x=2.75   ##seed value
for i in range(10):
    x=1+(1-3.5)*x
    print(x)

-5.875
15.6875
-38.21875
96.546875
-240.3671875
601.91796875
-1503.794921875
3760.4873046875
-9400.21826171875
23501.545654296875


## Inter Quartile Range

In [ ]:
 np.percentile

## Numpy Arrays

In [11]:
a=[1,2]

In [13]:
a=[[3,4],[5,6]]
a

[[3, 4], [5, 6]]

In [14]:
a[0][0]

3

In [15]:
a[0][1]

4

In [16]:
a[1][0]

5

In [17]:
a[1][1]

6

In [19]:
a[1],[2]

([5, 6], [2])

In [22]:
import numpy as np

In [24]:
a_n=np.array(a)
a_n

array([[3, 4],
       [5, 6]])

In [25]:
a_n[0,:]

array([3, 4])

In [26]:
a_n[1,:]

array([5, 6])

In [27]:
a_n.dtype

dtype('int32')

In [29]:
type(a_n)

numpy.ndarray

In [32]:
a_n.strides

(8, 4)

In [34]:
a_n + 1

array([[4, 5],
       [6, 7]])

In [35]:
a_n.shape

(2, 2)

In [37]:
b_n = np.array([1])
b_n

array([1])

In [38]:
b_n.shape

(1,)

# <center>Case Study</center>

In [58]:
import numpy as np

In [59]:
a = np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv",skiprows=1)

In [60]:
a

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [61]:
sachin_runs = a[:,1]

In [62]:
sachin_runs

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [63]:
np.mean(sachin_runs)

63.6

In [64]:
dravid_runs = a[:,2]

In [65]:
dravid_runs

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [66]:
np.mean(dravid_runs)

71.06666666666666

In [67]:
India_runs = a[:,3]
India_runs

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [68]:
np.mean(India_runs)

281.26666666666665

#### Man of the match

In [69]:
np.corrcoef(sachin_runs,India_runs)

array([[1.        , 0.70460106],
       [0.70460106, 1.        ]])

In [70]:
np.corrcoef(dravid_runs,India_runs)

array([[1.        , 0.44853003],
       [0.44853003, 1.        ]])

#### Opening slot

In [71]:
np.corrcoef(sachin_runs,dravid_runs)

array([[1.        , 0.04899219],
       [0.04899219, 1.        ]])